#!/usr/bin/perl -w
###########################################
# xx -- 
# Mike Schilli, 2005 (m@perlmeister.com)
###########################################
use strict;
use Sysadm::Install qw(:all);

use Expect;
use Data::Dumper;
use YAML qw(Dump LoadFile);

my $answers = LoadFile("/tmp/58.yml");
my @answers = @$answers;

my $i = 1;
my @patterns = map { $i++ % 2 ? quotemeta($_) : () } @answers;
my %answers  = @answers;

for my $pat (@patterns) {
    print "pattern='$pat'\n";
}

my $exp = Expect->new();
$exp->raw_pty(1);
$exp->spawn("./Configure")
    or die "Cannot spawn: $!\n";

{
  my ($matched_pattern_position, $error, $match,
      $before_match, $after_match) = 
        $exp->expect(60, map { -re => $_ } @patterns);

  if(defined $match) {
      #print "p=$match$after_match\n";
      $exp->send($answers{$match} . "\n");
      redo;
  }

}
